import { Inter } from 'next/font/google'
import './globals.css'
import AddUserClickContextProvider from '@/contexts/AddUserClickContext'
import AddUserContextProvider from '@/contexts/AddUserContext'
import AuthProvider from '@/components/AuthProvider'
import ProtectedRoute from '@/components/ProtectedRoute'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <ProtectedRoute>
        <AddUserClickContextProvider>
          <AddUserContextProvider>
            <html lang="en">
              <head>
                <link rel="icon" type="image/jpeg" sizes="96x96" href="/images/oficialia.jpg" />

                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Oficialia</title>
              </head>
              <body className={inter.className}>{children}</body>
            </html>
          </AddUserContextProvider>
        </AddUserClickContextProvider>
      </ProtectedRoute>
    </AuthProvider>
  )
}
